-- # Put the your SQL below migration seperator.
-- !UP

create table if not exists job_tags (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz default current_timestamp
);

alter table job_tags enable row level security;

create policy "all job tags are viewable by everyone." on job_tags
for select using (true);

create policy "everybody can insert data into job tags." on job_tags
for insert with check (true);

-- !DOWN

drop table if exists job_tags;
