-- # Put the your SQL below migration seperator.
-- !UP

create table if not exists post_job_submissions (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  telegram varchar(30) not null,
  role varchar(100) not null,
  email varchar(100) not null,
  organization varchar(100) not null,
  organization_website text not null,
  job_post_title varchar(300) not null,
  job_post_seniority_level varchar(30) not null,
  job_post_salary varchar(120) not null,
  job_post_contract_type varchar(30) not null,
  job_post_location varchar(100) not null,
  job_post_description text not null,
  created_at timestamptz default current_timestamp,
  updated_at timestamptz default current_timestamp
);

alter table post_job_submissions enable row level security;

create policy "all landing page job submissions are viewable by everyone." on post_job_submissions
for select using (true);

create policy "everybody can insert data into landing page job submissions." on post_job_submissions
for insert with check (true);

create trigger tr_mod_updated_at
before update on post_job_submissions
for each row
execute function moddatetime(updated_at);

-- !DOWN

drop trigger if exists tr_mod_updated_at on post_job_submissions;
drop table if exists post_job_submissions;
