-- # Put the your SQL below migration seperator.
-- !UP

create table if not exists contact_us_submissions (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  organization varchar(100) not null,
  email varchar(100) not null,
  telegram varchar(30) not null,
  details text not null,
  created_at timestamptz default current_timestamp,
  updated_at timestamptz default current_timestamp
);

alter table contact_us_submissions enable row level security;

create policy "all contact us submissions are viewable by everyone." on contact_us_submissions
for select using (true);

create policy "everybody can insert data into contact us submissions." on contact_us_submissions
for insert with check (true);

create trigger tr_mod_updated_at
before update on contact_us_submissions
for each row
execute function moddatetime(updated_at);

-- !DOWN

drop trigger if exists tr_mod_updated_at on contact_us_submissions;
drop table if exists contact_us_submissions;
